# Generated by Django 5.2.17 on 2026-08-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('tax_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax Number')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('currency', models.CharField(default='JOD', max_length=10, verbose_name='Currency')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logo/', verbose_name='Logo')),
                ('expiration_warning_days', models.PositiveIntegerField(default=30, verbose_name='Expiration Warning Days')),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
    ]
