# Generated by Django 5.2.17 on 2026-08-12 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_options_alter_customer_address_and_more'),
        ('finance', '0004_normalize_purchase_source_type'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'verbose_name': 'Journal Entry', 'verbose_name_plural': 'Journal Entries'},
        ),
        migrations.AlterModelOptions(
            name='journalentryline',
            options={'verbose_name': 'Journal Entry Line', 'verbose_name_plural': 'Journal Entry Lines'},
        ),
        migrations.AlterModelOptions(
            name='paymentvoucher',
            options={'verbose_name': 'Payment Voucher', 'verbose_name_plural': 'Payment Vouchers'},
        ),
        migrations.AlterModelOptions(
            name='receiptvoucher',
            options={'verbose_name': 'Receipt Voucher', 'verbose_name_plural': 'Receipt Vouchers'},
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], max_length=20, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='account',
            name='allow_posting',
            field=models.BooleanField(default=True, verbose_name='Allow Posting'),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='finance.account', verbose_name='Parent Account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry_number',
            field=models.CharField(max_length=30, unique=True, verbose_name='Entry Number'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Source ID'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('purchase', 'Purchase'), ('pos_sale', 'POS Sale'), ('receipt', 'Receipt Voucher'), ('payment', 'Payment Voucher'), ('waste', 'Waste & Loss'), ('sales_return', 'Sales Return')], default='manual', max_length=30, verbose_name='Source Type'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='finance.account', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='credit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Credit'),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='debit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Debit'),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.journalentry', verbose_name='Journal Entry'),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='suppliers.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_vouchers', to='finance.account', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payment_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='paid_to',
            field=models.CharField(max_length=200, verbose_name='Paid To'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank', 'Bank')], max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_vouchers', to='suppliers.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='voucher_number',
            field=models.CharField(max_length=30, unique=True, verbose_name='Voucher Number'),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_vouchers', to='finance.account', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_receipt_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_vouchers', to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank', 'Bank')], max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='received_from',
            field=models.CharField(max_length=200, verbose_name='Received From'),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='voucher_number',
            field=models.CharField(max_length=30, unique=True, verbose_name='Voucher Number'),
        ),
    ]
