# Generated by Django 5.2.17 on 2026-08-13 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_account_options_alter_journalentry_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='reversal_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_entry', to='finance.journalentry', verbose_name='Reversal Of'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversal_reason',
            field=models.TextField(blank=True, verbose_name='Reversal Reason'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reversed At'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='Reversed By'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('purchase', 'Purchase'), ('pos_sale', 'POS Sale'), ('receipt', 'Receipt Voucher'), ('payment', 'Payment Voucher'), ('waste', 'Waste & Loss'), ('sales_return', 'Sales Return'), ('reversal', 'Journal Reversal')], default='manual', max_length=30, verbose_name='Source Type'),
        ),
    ]
