# Generated by Django 5.2.17 on 2026-08-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_journalentry_reversal_of_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('rate', models.DecimalField(decimal_places=3, default=0, help_text='Percentage, for example 16.000 for 16%.', max_digits=6, verbose_name='Tax Rate')),
                ('subject_to_tax', models.BooleanField(default=True, help_text='Clear this for exempt items so no tax is calculated.', verbose_name='Subject To Tax')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Tax Rate',
                'verbose_name_plural': 'Tax Rates',
                'ordering': ('code',),
            },
        ),
    ]
