# Generated by Django 5.2.17 on 2026-08-19 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_fiscalyear_fiscalperiod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalperiod',
            name='close_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Close Reason'),
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='close_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Close Reason'),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.CreateModel(
            name='FiscalPeriodAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed')], max_length=10, verbose_name='Action')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='Performed At')),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='finance.fiscalyear', verbose_name='Fiscal Year')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_period_actions', to=settings.AUTH_USER_MODEL, verbose_name='Performed By')),
                ('period', models.ForeignKey(blank=True, help_text='Empty for an action on the complete fiscal year.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='finance.fiscalperiod', verbose_name='Fiscal Period')),
            ],
            options={
                'verbose_name': 'Fiscal Period Action',
                'verbose_name_plural': 'Fiscal Period Actions',
                'ordering': ('-performed_at', '-id'),
            },
        ),
    ]
