# Generated by Django 5.2.17 on 2026-08-19 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_options_alter_customer_address_and_more'),
        ('finance', '0009_fiscalperiod_close_reason_fiscalperiod_notes_and_more'),
        ('suppliers', '0002_alter_supplier_options_alter_supplier_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('receivable', 'Receivable'), ('payable', 'Payable')], max_length=20)),
                ('document_number', models.CharField(max_length=100)),
                ('document_date', models.DateField()),
                ('due_date', models.DateField()),
                ('original_amount', models.DecimalField(decimal_places=3, max_digits=14)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='open_items', to='customers.customer')),
                ('journal_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='open_item', to='finance.journalentryline')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='open_items', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['due_date', 'document_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OpenItemAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=14)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_open_item_allocations', to=settings.AUTH_USER_MODEL)),
                ('journal_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='open_item_allocations', to='finance.journalentryline')),
                ('open_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.openitem')),
            ],
            options={
                'ordering': ['allocation_date', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='openitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('customer__isnull', False), ('item_type', 'receivable'), ('supplier__isnull', True)), models.Q(('customer__isnull', True), ('item_type', 'payable'), ('supplier__isnull', False)), _connector='OR'), name='open_item_has_correct_party'),
        ),
        migrations.AddConstraint(
            model_name='openitem',
            constraint=models.CheckConstraint(condition=models.Q(('original_amount__gt', 0)), name='open_item_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='openitemallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='open_item_allocation_amount_positive'),
        ),
    ]
