# Generated by Django 5.2.17 on 2026-08-19 09:38

from django.db import migrations, models


def configure_existing_cash_flow_data(apps, schema_editor):
    Account = apps.get_model("finance", "Account")
    JournalEntry = apps.get_model("finance", "JournalEntry")

    Account.objects.filter(code__in=("1100", "1200", "1210")).update(
        is_cash_equivalent=True
    )
    JournalEntry.objects.filter(
        source_type__in=("receipt", "payment", "pos_sale", "purchase")
    ).update(cash_flow_activity="operating")

    reversals = JournalEntry.objects.filter(
        source_type="reversal",
        reversal_of__isnull=False,
    ).select_related("reversal_of")
    for reversal in reversals:
        reversal.cash_flow_activity = reversal.reversal_of.cash_flow_activity
        reversal.save(update_fields=["cash_flow_activity"])


def reset_cash_flow_data(apps, schema_editor):
    Account = apps.get_model("finance", "Account")
    JournalEntry = apps.get_model("finance", "JournalEntry")
    Account.objects.filter(code__in=("1100", "1200", "1210")).update(
        is_cash_equivalent=False
    )
    JournalEntry.objects.update(cash_flow_activity="none")


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_openitem_openitemallocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_cash_equivalent',
            field=models.BooleanField(default=False, help_text='Include this account in the cash-flow statement.', verbose_name='Cash or Cash Equivalent'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='cash_flow_activity',
            field=models.CharField(choices=[('none', 'No Cash-Flow Effect'), ('operating', 'Operating Activity'), ('investing', 'Investing Activity'), ('financing', 'Financing Activity')], default='none', help_text='Required when this journal changes cash or bank balances.', max_length=20, verbose_name='Cash-Flow Activity'),
        ),
        migrations.RunPython(
            configure_existing_cash_flow_data,
            reset_cash_flow_data,
        ),
    ]
