# Generated by Django 5.2.17 on 2026-08-19 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_account_is_cash_equivalent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, max_length=150, verbose_name='User snapshot')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('posted', 'Posted'), ('reversed', 'Reversed'), ('closed', 'Closed'), ('reopened', 'Reopened')], max_length=20, verbose_name='Action')),
                ('entity_type', models.CharField(db_index=True, max_length=80, verbose_name='Record type')),
                ('entity_label', models.CharField(max_length=120, verbose_name='Record type label')),
                ('object_id', models.CharField(db_index=True, max_length=64, verbose_name='Record ID')),
                ('object_repr', models.CharField(max_length=255, verbose_name='Record')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Changes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date and time')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Finance Audit Log',
                'verbose_name_plural': 'Finance Audit Logs',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
