# Generated by Django 5.2.17 on 2026-08-19 13:48

from django.db import migrations, models


def create_adjustment_accounts(apps, schema_editor):
    Account = apps.get_model("finance", "Account")
    for code, name, account_type in (
        ("4300", "Inventory Adjustment Gain", "revenue"),
        ("6310", "Inventory Adjustment Loss", "expense"),
    ):
        Account.objects.get_or_create(
            code=code,
            defaults={
                "name": name,
                "account_type": account_type,
                "parent": None,
                "allow_posting": True,
                "is_active": True,
                "is_cash_equivalent": False,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_financeauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('purchase', 'Purchase'), ('pos_sale', 'POS Sale'), ('receipt', 'Receipt Voucher'), ('payment', 'Payment Voucher'), ('waste', 'Waste & Loss'), ('stock_adjustment', 'Stock Adjustment'), ('sales_return', 'Sales Return'), ('reversal', 'Journal Reversal')], default='manual', max_length=30, verbose_name='Source Type'),
        ),
        migrations.RunPython(create_adjustment_accounts, migrations.RunPython.noop),
    ]
