# Generated by Django 5.2.17 on 2026-08-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_stock_adjustment_posting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('purchase', 'Purchase'), ('pos_sale', 'POS Sale'), ('pos_session', 'POS Register Session'), ('receipt', 'Receipt Voucher'), ('payment', 'Payment Voucher'), ('waste', 'Waste & Loss'), ('stock_adjustment', 'Stock Adjustment'), ('sales_return', 'Sales Return'), ('reversal', 'Journal Reversal')], default='manual', max_length=30, verbose_name='Source Type'),
        ),
    ]
