# Generated by Django 5.2.17 on 2026-08-12 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_wasteloss_status'),
        ('purchasing', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='stockbalance',
            options={'verbose_name': 'Stock Balance', 'verbose_name_plural': 'Stock Balances'},
        ),
        migrations.AlterModelOptions(
            name='stockbatch',
            options={'verbose_name': 'Stock Batch', 'verbose_name_plural': 'Stock Batches'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'verbose_name': 'Stock Movement', 'verbose_name_plural': 'Stock Movements'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Warehouse', 'verbose_name_plural': 'Warehouses'},
        ),
        migrations.AlterModelOptions(
            name='warehousetransfer',
            options={'verbose_name': 'Warehouse Transfer', 'verbose_name_plural': 'Warehouse Transfers'},
        ),
        migrations.AlterModelOptions(
            name='warehousetransferitem',
            options={'verbose_name': 'Warehouse Transfer Item', 'verbose_name_plural': 'Warehouse Transfer Items'},
        ),
        migrations.AlterModelOptions(
            name='wasteloss',
            options={'verbose_name': 'Waste Loss', 'verbose_name_plural': 'Waste Losses'},
        ),
        migrations.AlterModelOptions(
            name='wastelossitem',
            options={'verbose_name': 'Waste Loss Item', 'verbose_name_plural': 'Waste Loss Items'},
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='inventory.category', verbose_name='Parent Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Barcode'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_stock',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Minimum Stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Purchase Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Selling Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='track_expiration',
            field=models.BooleanField(default=False, verbose_name='Track Expiration'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.unit', verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='stockbalance',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='inventory.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='stockbalance',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='stockbalance',
            name='reserved_quantity',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Reserved Quantity'),
        ),
        migrations.AlterField(
            model_name='stockbalance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='stockbalance',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='inventory.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='batch_number',
            field=models.CharField(max_length=100, verbose_name='Batch Number'),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='inventory.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='purchase_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='purchasing.purchaseinvoiceitem', verbose_name='Purchase Item'),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='quantity_received',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantity Received'),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='quantity_remaining',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantity Remaining'),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='received_date',
            field=models.DateField(verbose_name='Received Date'),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('DEPLETED', 'Depleted'), ('BLOCKED', 'Blocked')], default='ACTIVE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='suppliers.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='unit_cost',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Unit Cost'),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='inventory.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.stockbatch', verbose_name='Stock Batch'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('OPENING_BALANCE', 'Opening Balance'), ('PURCHASE', 'Purchase'), ('PURCHASE_RETURN', 'Purchase Return'), ('SALE', 'Sale'), ('SALE_RETURN', 'Sale Return'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('WASTE', 'Waste'), ('DAMAGE', 'Damage'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out')], max_length=30, verbose_name='Movement Type'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reference_id',
            field=models.BigIntegerField(verbose_name='Reference ID'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reference_type',
            field=models.CharField(max_length=100, verbose_name='Reference Type'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='unit_cost',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Unit Cost'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='symbol',
            field=models.CharField(max_length=20, verbose_name='Symbol'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='warehousetransfer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='warehousetransfer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='warehousetransfer',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='warehousetransfer',
            name='destination_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='inventory.warehouse', verbose_name='Destination Warehouse'),
        ),
        migrations.AlterField(
            model_name='warehousetransfer',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='warehousetransfer',
            name='source_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='inventory.warehouse', verbose_name='Source Warehouse'),
        ),
        migrations.AlterField(
            model_name='warehousetransfer',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='warehousetransfer',
            name='transfer_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Transfer Number'),
        ),
        migrations.AlterField(
            model_name='warehousetransferitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_items', to='inventory.stockbatch', verbose_name='Stock Batch'),
        ),
        migrations.AlterField(
            model_name='warehousetransferitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_items', to='inventory.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='warehousetransferitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='warehousetransferitem',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.warehousetransfer', verbose_name='Transfer'),
        ),
        migrations.AlterField(
            model_name='wasteloss',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='wasteloss',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_loss_records', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='wasteloss',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='wasteloss',
            name='document_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Document Number'),
        ),
        migrations.AlterField(
            model_name='wasteloss',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='wasteloss',
            name='reason',
            field=models.CharField(choices=[('EXPIRED', 'Expired'), ('DAMAGED', 'Damaged'), ('SPOILED', 'Spoiled'), ('BROKEN', 'Broken'), ('MISSING', 'Missing'), ('OTHER', 'Other')], max_length=30, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='wasteloss',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_losses', to='inventory.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='wastelossitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_loss_items', to='inventory.stockbatch', verbose_name='Stock Batch'),
        ),
        migrations.AlterField(
            model_name='wastelossitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_loss_items', to='inventory.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='wastelossitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='wastelossitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Total Cost'),
        ),
        migrations.AlterField(
            model_name='wastelossitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Unit Cost'),
        ),
        migrations.AlterField(
            model_name='wastelossitem',
            name='waste_loss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.wasteloss', verbose_name='Waste Loss'),
        ),
    ]
