# Generated by Django 5.2.17 on 2026-08-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_image_product_maximum_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Arabic Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='English Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Arabic Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='English Name'),
        ),
        migrations.AddField(
            model_name='unit',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Arabic Name'),
        ),
        migrations.AddField(
            model_name='unit',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='English Name'),
        ),
    ]
