# Generated by Django 5.2.17 on 2026-08-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_category_name_remove_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_ar',
            field=models.CharField(default='', max_length=255, verbose_name='Arabic Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(default='', max_length=255, verbose_name='English Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ar',
            field=models.CharField(default='', max_length=255, verbose_name='Arabic Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(default='', max_length=255, verbose_name='English Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unit',
            name='name_ar',
            field=models.CharField(default='', max_length=100, verbose_name='Arabic Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unit',
            name='name_en',
            field=models.CharField(default='', max_length=100, verbose_name='English Name'),
            preserve_default=False,
        ),
    ]
