# Generated by Django 5.2.17 on 2026-08-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_category_name_ar_alter_category_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousetransferitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Unit Cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ar',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Arabic Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(db_index=True, max_length=255, verbose_name='English Name'),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='expiration_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
    ]
