# Generated by Django 5.2.17 on 2026-08-18 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_taxrate'),
        ('inventory', '0009_warehousetransferitem_unit_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sellable',
            field=models.BooleanField(default=True, help_text='Clear this for items that are only bought, never sold.', verbose_name='Is Sellable'),
        ),
        migrations.AddField(
            model_name='product',
            name='maximum_discount',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Largest discount percentage allowed on this item.', max_digits=6, verbose_name='Maximum Discount'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.ForeignKey(blank=True, help_text='Leave empty to treat this item as not taxed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='finance.taxrate', verbose_name='Tax Rate'),
        ),
    ]
