# Generated by Django 5.2.17 on 2026-08-12 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_options_alter_customer_address_and_more'),
        ('inventory', '0005_alter_category_options_alter_product_options_and_more'),
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pospayment',
            options={'verbose_name': 'POS Payment', 'verbose_name_plural': 'POS Payments'},
        ),
        migrations.AlterModelOptions(
            name='possale',
            options={'verbose_name': 'POS Sale', 'verbose_name_plural': 'POS Sales'},
        ),
        migrations.AlterModelOptions(
            name='possaleitem',
            options={'verbose_name': 'POS Sale Item', 'verbose_name_plural': 'POS Sale Items'},
        ),
        migrations.AlterField(
            model_name='pospayment',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='pospayment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_payments', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='pospayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank', 'Bank Transfer'), ('credit', 'Store Credit')], max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='pospayment',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Received At'),
        ),
        migrations.AlterField(
            model_name='pospayment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference Number'),
        ),
        migrations.AlterField(
            model_name='pospayment',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos.possale', verbose_name='Sale'),
        ),
        migrations.AlterField(
            model_name='possale',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sales', to=settings.AUTH_USER_MODEL, verbose_name='Cashier'),
        ),
        migrations.AlterField(
            model_name='possale',
            name='change_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Change Amount'),
        ),
        migrations.AlterField(
            model_name='possale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sales', to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='possale',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='possale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Discount Amount'),
        ),
        migrations.AlterField(
            model_name='possale',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='possale',
            name='paid_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Paid Amount'),
        ),
        migrations.AlterField(
            model_name='possale',
            name='sale_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Sale Number'),
        ),
        migrations.AlterField(
            model_name='possale',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='possale',
            name='subtotal',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='possale',
            name='tax_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Tax Amount'),
        ),
        migrations.AlterField(
            model_name='possale',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='possale',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sales', to='inventory.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='possaleitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sale_items', to='inventory.stockbatch', verbose_name='Stock Batch'),
        ),
        migrations.AlterField(
            model_name='possaleitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Discount Amount'),
        ),
        migrations.AlterField(
            model_name='possaleitem',
            name='line_total',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Line Total'),
        ),
        migrations.AlterField(
            model_name='possaleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sale_items', to='inventory.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='possaleitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='possaleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.possale', verbose_name='Sale'),
        ),
        migrations.AlterField(
            model_name='possaleitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Tax Amount'),
        ),
        migrations.AlterField(
            model_name='possaleitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Unit Cost'),
        ),
        migrations.AlterField(
            model_name='possaleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Unit Price'),
        ),
    ]
