# Generated by Django 5.2.17 on 2026-08-16 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_category_options_alter_product_options_and_more'),
        ('pos', '0002_alter_pospayment_options_alter_possale_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POSSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.CharField(max_length=100, unique=True, verbose_name='Session Number')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=20, verbose_name='Status')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Opened At')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed At')),
                ('opening_balance', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Opening Cash Float')),
                ('closing_balance_expected', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Expected Cash')),
                ('closing_balance_actual', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Actual Counted Cash')),
                ('difference', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Difference / Shortage')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Session Notes')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Cashier')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sessions', to='inventory.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'POS Session',
                'verbose_name_plural': 'POS Sessions',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='POSCashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'Cash In / Add Float'), ('OUT', 'Cash Out / Drop')], max_length=10, verbose_name='Transaction Type')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Amount')),
                ('reason', models.CharField(max_length=255, verbose_name='Reason / Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_cash_transactions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_transactions', to='pos.possession', verbose_name='POS Session')),
            ],
            options={
                'verbose_name': 'POS Cash Transaction',
                'verbose_name_plural': 'POS Cash Transactions',
            },
        ),
        migrations.AddField(
            model_name='possale',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='pos.possession', verbose_name='POS Session'),
        ),
    ]
