# Generated by Django 5.2.17 on 2026-08-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_possession_poscashtransaction_possale_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possale',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('HELD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20, verbose_name='Status'),
        ),
    ]
