# Generated by Django 5.2.17 on 2026-08-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_alter_possale_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage (%)'), ('FIXED', 'Fixed Amount')], default='PERCENTAGE', max_length=20, verbose_name='Discount Type')),
                ('value', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Discount Value')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Max Discount Amount')),
                ('min_order_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Minimum Order Amount')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Usage Limit')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Times Used')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Valid From')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Valid To')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Discount Code',
                'verbose_name_plural': 'Discount Codes',
            },
        ),
    ]
