# Generated by Django 5.2.17 on 2026-08-19 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='possale',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.discountcode'),
        ),
    ]
