# Generated by Django 5.2.17 on 2026-08-12 12:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_category_options_alter_product_options_and_more'),
        ('purchasing', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseinvoice',
            options={'verbose_name': 'Purchase Invoice', 'verbose_name_plural': 'Purchase Invoices'},
        ),
        migrations.AlterModelOptions(
            name='purchaseinvoiceitem',
            options={'verbose_name': 'Purchase Invoice Item', 'verbose_name_plural': 'Purchase Invoice Items'},
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='additional_expenses',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Additional Expenses'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_purchase_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Discount Amount'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_date',
            field=models.DateField(verbose_name='Invoice Date'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_number',
            field=models.CharField(max_length=30, unique=True, verbose_name='Invoice Number'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Paid Amount'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit')], default='credit', max_length=20, verbose_name='Payment Type'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='suppliers.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='supplier_invoice_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Supplier Invoice Number'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Tax Amount'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='inventory.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Batch Number'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Discount Amount'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='line_total',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Line Total'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='inventory.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='purchase_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchasing.purchaseinvoice', verbose_name='Purchase Invoice'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Tax Amount'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unit Cost'),
        ),
    ]
