# Generated by Django 5.2.17 on 2026-08-12 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_alter_customer_options_alter_customer_address_and_more'),
        ('inventory', '0005_alter_category_options_alter_product_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(max_length=50, unique=True, verbose_name='Quotation Number')),
                ('date', models.DateField(verbose_name='Date')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('subtotal', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Subtotal')),
                ('discount_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Discount Amount')),
                ('tax_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Tax Amount')),
                ('total', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Total')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Quotation',
                'verbose_name_plural': 'Quotations',
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Unit Price')),
                ('discount_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Discount Amount')),
                ('tax_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Tax Amount')),
                ('line_total', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Line Total')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.quotation', verbose_name='Quotation')),
            ],
            options={
                'verbose_name': 'Quotation Item',
                'verbose_name_plural': 'Quotation Items',
            },
        ),
    ]
