# Generated by Django 5.2.17 on 2026-08-20 08:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_alter_customer_options_alter_customer_address_and_more'),
        ('finance', '0015_alter_journalentry_source_type'),
        ('inventory', '0010_product_is_sellable_product_maximum_discount_and_more'),
        ('quotations', '0002_alter_quotation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Invoice Number')),
                ('invoice_date', models.DateField(verbose_name='Invoice Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit')], default='credit', max_length=10, verbose_name='Payment Type')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled'), ('credited', 'Credited')], default='draft', max_length=15, verbose_name='Status')),
                ('subtotal', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Subtotal')),
                ('discount_amount', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Discount Amount')),
                ('tax_amount', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Tax Amount')),
                ('total', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Total')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Posted At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sales_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='customers.customer', verbose_name='Customer')),
                ('payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_sales_invoices', to='finance.account', verbose_name='Cash / Bank Account')),
                ('quotation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice', to='quotations.quotation', verbose_name='Quotation')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='inventory.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Sales Invoice',
                'verbose_name_plural': 'Sales Invoices',
                'ordering': ('-invoice_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SalesCreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_note_number', models.CharField(max_length=50, unique=True, verbose_name='Credit Note Number')),
                ('date', models.DateField(verbose_name='Date')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=15, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Posted At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sales_credit_notes', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='credit_note', to='sales.salesinvoice', verbose_name='Sales Invoice')),
            ],
            options={
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Unit Price')),
                ('unit_cost', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Unit Cost')),
                ('discount_amount', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Discount Amount')),
                ('tax_amount', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Tax Amount')),
                ('line_total', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Line Total')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesinvoice', verbose_name='Sales Invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_items', to='inventory.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Sales Invoice Item',
                'verbose_name_plural': 'Sales Invoice Items',
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceStockAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=3, max_digits=14)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_allocations', to='inventory.stockbatch')),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_allocations', to='sales.salesinvoiceitem')),
            ],
        ),
    ]
